# Generated by Django 3.2.8 on 2022-02-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_login',
            new_name='UserData',
        ),
    ]
