# Generated by Django 3.2.8 on 2022-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_login_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_log',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='u_sign',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pwd1', models.CharField(max_length=500)),
                ('pwd2', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
